bf16: true
beta: 0.01
temperature_alpha: 0.0001
do_eval: true
eval_steps: 200
loss_type: NCA
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: zephyr-7b-NCA-qlora
learning_rate: 0.000005
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1280
max_prompt_length: 512
num_train_epochs: 1
optim: paged_adamw_32bit
output_dir: nca
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "epoch"
save_total_limit: null
seed: 42
warmup_ratio: 0.1
