bf16: true
beta: 2.5
gamma_beta_ratio: 0.55
do_eval: true
eval_steps: 400
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: simpo-exps
learning_rate: 0.000001
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 1280
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
run_name: simpo
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
